k9s:
  liveViewAutoRefresh: true 
  refreshRate: 2
  enableMouse: true
  logger:
    tail: 200
  clusters:
    default:
      namespace:
        active: default 
      view:
        active: po
      featureGates:
        nodeShell: true 
    kind:
      namespace:
        active: all
        favorites:
        - all
        - kube-system
        - default
      view:
        active: dp
  screenDumpDir: /tmp
