k9s:
  cluster: freshlab
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - authelia
      - flask
      - arc
      - default
      - budget
      - argocd
      - dex
      - holmesgpt
  view:
    active: v1/namespaces
  featureGates:
    nodeShell: false
  proxy: null
