k9s:
  cluster: k3d-kubefirst
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - argo
    - default
  view:
    active: service
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
