k9s:
  cluster: default
  skin: catppuccin-mocha-transparent
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - argocd
    - default
  view:
    active: pod
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
